global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using Eventide.Components;
global using Eventide.Content;
global using Eventide.Input;
global using SFML.System;
global using SFML.Window;
global using SFMLSound = SFML.Audio.Sound;
global using SFMLSoundBuffer = SFML.Audio.SoundBuffer;
global using SFMLCircle = SFML.Graphics.CircleShape;
global using SFMLFont = SFML.Graphics.Font;
global using SFMLRectangle = SFML.Graphics.RectangleShape;
global using SFMLRenderTexture = SFML.Graphics.RenderTexture;
global using SFMLRenderWindow = SFML.Graphics.RenderWindow;
global using SFMLSprite = SFML.Graphics.Sprite;
global using SFMLText = SFML.Graphics.Text;
global using SFMLTexture = SFML.Graphics.Texture;
global using SFMLView = SFML.Graphics.View;
